### ISSUE TITLE
Class Goals

### ISSUE THREAD

**Issue by MiguelIronHack** [MiguelIronHack/test#1]
## My Goals

-[ ] Learn how to use Issues on GitHub

@cupidstrick What other goals should I add here
![crow](https://user-images.githubusercontent.com/47717188/52914755-7e963080-32cc-11e9-9c59-8da89a58aa5e.jpg)

**Comment by CupidsTrick** [comment]
@MiguelIronHack Test.

**Comment by MiguelIronHack** [comment]
@CupidsTrick Test
